### PR TITLE
Correct alignment of icons

### PR DESCRIPTION
**Pull request by mu-arch**
- corrected alignment of icons to filenames
- changed vertical spacing of li elements to account for increased height of anchors

### CODE REVIEW

**Comment by mu-arch** [comment]
Demo of improvement
Screenshot_20211119_120426
s.

**Comment by weihanglo** [comment]
Sorry but I didn't get the point. Here is what this PR looks like on my machine (macOS Monteray with Firefox)

image

**Comment by mu-arch** [comment]
Hmm. I have a Mac computer, let me investigate it on there.

**Comment by weihanglo** [comment]
Thank you for the PR. Unfortunately I have no time working on it. See #108.

**Pull request closed without merging**
